language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - sudo apt-get update
  - sudo apt-get install nasm -y
  - npm install
  - npm install hexo-all-minifier --save

script:
  - hexo clean
  - git clone https://github.com/Nexus6pBar/Nexus6pBar.github.io.git public -b master --depth=1 
  - cd public
  - git rm -rf .
  - cd ..
  - hexo g
  - cp ./404/404.html ./public
  - cp ./404/game.js ./public/js
  - cp ./404/game.css ./public/css
  - cp -r ./404/assets ./public
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_Token}
  keep_history: true
  local_dir: ./public
  target_branch: master
  on:
    branch: source

env:
 global:
   - GH_REF: github.com/Nexus6pBar/Nexus6pBar.github.io.git
   - Coding_REF: git.dev.tencent.com/Neuron/Nexus6pBar.git
