language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - sudo apt-get update
  - sudo apt-get install nasm -y
  - npm install
  - npm install hexo-all-minifier --save

#before_script:
 # - npm install -g gulp
  

script:
  - hexo clean
  - hexo g

after_script:
  - cp ./404/404.html ./public
  - cp ./404/game.js ./public/js
  - cp ./404/game.css ./public/css
  - cp -r ./404/assets ./public
  - cd ./public
  - git init
  - git config user.name "singleNeuron"
  - git config user.email "liziyuan123456@yeah.net"
  - git add .
  - git remote add origin https://github.com/Nexus6pBar/Nexus6pBar.github.io.git
  - git commit -m "#$TRAVIS_BUILD_NUMBER deployed by Travis-CI"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master
  - git push --force --quiet "https://${Coding_Token}@${Coding_REF}" master:master
# E: Build LifeCycle


env:
 global:
   - GH_REF: github.com/BaiduNexus6pBar/BaiduNexus6pBar.github.io.git
   - Coding_REF: git.coding.net/Neuron/Nexus6pBar.git
