language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "singleNeuron"
  - git config user.email "liziyuan123456@yeah.net"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master
# E: Build LifeCycle


env:
 global:
   - GH_REF: github.com/BaiduNexus6pBar/BaiduNexus6pBar.github.io.git
