language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 # - npm install -g gulp
   - npm install -g hexo-all-minifier

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "singleNeuron"
  - git config user.email "liziyuan123456@yeah.net"
  - git add .
  - git remote add origin master https://github.com/Nexus6pBar/Nexus6pBar.github.io.git
  - git commit -m "#$TRAVIS_BUILD_NUMBER deployed by Travis-CI"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master
# E: Build LifeCycle


env:
 global:
   - GH_REF: github.com/BaiduNexus6pBar/BaiduNexus6pBar.github.io.git
